pub const glyph_pixels = @import("renderer/glyph_pixels.zig"); // 합성 글리프 공유 RGBA8 픽셀 프리미티브(슬롯 검증·clear·setPixel·fillRect·대각선). 중립.
pub const block_glyph = @import("renderer/block_glyph.zig"); // Block Elements(U+2580~259F) 합성 — 폰트 대신 셀에 사각형 coverage(이음매 없는 타일링). 중립.
pub const box_glyph = @import("renderer/box_glyph.zig"); // Box-drawing(U+2500~257F 전체) 합성 — 폰트 대신 셀에 선/면(이음매 없는 연결). 중립.
pub const powerline_glyph = @import("renderer/powerline_glyph.zig"); // Powerline(U+E0B0~E0BF) 합성 — 삼각형·반원 separator를 셀에 꽉 차게. 중립.
pub const braille_glyph = @import("renderer/braille_glyph.zig"); // Braille(U+2800~28FF) 합성 — 2열×4행 8점 비트마스크를 셀 격자에 스냅. 중립.
pub const legacy_mosaic_glyph = @import("renderer/legacy_mosaic_glyph.zig"); // Legacy Computing 블록 모자이크(sextant U+1FB00~·octant U+1CD00~) 합성. 중립.
pub const draw_list = @import("renderer/draw_list.zig");
pub const frame_probe = @import("renderer/frame_probe.zig");
pub const font_identity = @import("renderer/font_identity.zig");
pub const glyph_atlas = @import("renderer/glyph_atlas.zig");
pub const glyph_frame = @import("renderer/glyph_frame.zig");
pub const glyph_layout = @import("renderer/glyph_layout.zig");
pub const glyph_quads = @import("renderer/glyph_quads.zig");
pub const glyph_raster = @import("renderer/glyph_raster.zig");
pub const metal_frame = @import("renderer/metal_frame.zig"); // 중립 frame DTO 투영(platform/macos→renderer 이주, §8). 이름만 "Metal" — OS 의존 없음(NativeMetalCell·MetalFrame extern). 백엔드(Metal/WebGPU)가 공유.
pub const shaped_records = @import("renderer/shaped_records.zig");
pub const state = @import("renderer/state.zig");
pub const types = @import("renderer/types.zig");

pub const AtlasTextureSize = glyph_quads.AtlasTextureSize;
pub const AtlasInvalidation = glyph_atlas.AtlasInvalidation;
pub const AtlasInvalidationReason = glyph_atlas.AtlasInvalidationReason;
pub const AtlasLookup = glyph_atlas.AtlasLookup;
pub const AtlasSlot = glyph_atlas.AtlasSlot;
pub const AtlasSlotId = glyph_atlas.AtlasSlotId;
pub const AtlasStats = glyph_atlas.AtlasStats;
pub const Backend = types.Backend;
pub const ColorGlyphKind = glyph_layout.ColorGlyphKind;
pub const CursorOverlay = draw_list.CursorOverlay;
pub const DrawCell = draw_list.DrawCell;
pub const DrawList = draw_list.DrawList;
pub const DrawOverlay = draw_list.DrawOverlay;
pub const FakeFontBackend = glyph_layout.FakeFontBackend;
pub const FakeGlyphRasterizer = glyph_raster.FakeGlyphRasterizer;
pub const GlyphAtlas = glyph_atlas.GlyphAtlas;
pub const GlyphAtlasConfig = glyph_atlas.GlyphAtlasConfig;
pub const FontIdentity = font_identity.FontIdentity;
pub const FontIdentityError = font_identity.FontIdentityError;
pub const FontIdentityKey = font_identity.FontIdentityKey;
pub const FontIdentityRegistry = font_identity.FontIdentityRegistry;
pub const FontId = glyph_layout.FontId;
pub const GlyphFrame = glyph_frame.GlyphFrame;
pub const GlyphQuadError = glyph_quads.GlyphQuadError;
pub const GlyphFrameStats = glyph_frame.GlyphFrameStats;
pub const GlyphQuad = glyph_quads.GlyphQuad;
pub const GlyphQuadFrame = glyph_quads.GlyphQuadFrame;
pub const GlyphQuadFrameStats = glyph_quads.GlyphQuadFrameStats;
pub const GlyphUvRect = glyph_quads.GlyphUvRect;
pub const GlyphRasterError = glyph_raster.GlyphRasterError;
pub const GlyphRasterFrame = glyph_raster.GlyphRasterFrame;
pub const GlyphRasterFrameConfig = glyph_raster.GlyphRasterFrameConfig;
pub const GlyphRasterFrameStats = glyph_raster.GlyphRasterFrameStats;
pub const GlyphRasterRequest = glyph_raster.GlyphRasterRequest;
pub const GlyphRasterResult = glyph_raster.GlyphRasterResult;
pub const GlyphRasterSkip = glyph_raster.GlyphRasterSkip;
pub const GlyphRasterSkipReason = glyph_raster.GlyphRasterSkipReason;
pub const GlyphRasterUpload = glyph_raster.GlyphRasterUpload;
pub const GlyphCacheKey = glyph_layout.GlyphCacheKey;
pub const GlyphId = glyph_layout.GlyphId;
pub const GlyphRun = glyph_layout.GlyphRun;
pub const GlyphRunList = glyph_layout.GlyphRunList;
pub const GlyphUpload = glyph_frame.GlyphUpload;
pub const RasterStyleFlags = glyph_layout.RasterStyleFlags;
pub const RenderFrame = types.RenderFrame;
pub const RenderFrameStats = frame_probe.RenderFrameStats;
pub const RendererState = state.RendererState;
pub const RendererStateConfig = state.RendererStateConfig;
pub const renderFrameStats = frame_probe.renderFrameStats;
pub const writeRenderFrameStats = frame_probe.writeRenderFrameStats;
pub const ShapeResult = glyph_layout.ShapeResult;
pub const ShapedGlyphRecord = shaped_records.ShapedGlyphRecord;
pub const ShapedGlyphRunList = shaped_records.ShapedGlyphRunList;
pub const ShapedGlyphSurface = shaped_records.ShapedGlyphSurface;
pub const TextLayoutConfig = glyph_layout.TextLayoutConfig;
pub const LineOverlay = draw_list.LineOverlay;
pub const LineKind = draw_list.LineKind;
pub const buildDrawList = draw_list.buildDrawList;
pub const buildGlyphQuadFrame = glyph_quads.buildGlyphQuadFrame;
pub const buildGlyphRasterFrame = glyph_raster.buildGlyphRasterFrame;
pub const buildGlyphRunList = glyph_layout.buildGlyphRunList;
pub const buildGlyphRunListFromShapedRecords = shaped_records.buildGlyphRunListFromShapedRecords;
pub const buildGlyphRunListFromShapedRecordsWithSurface = shaped_records.buildGlyphRunListFromShapedRecordsWithSurface;
pub const initialBackendForMacOS = types.initialBackendForMacOS;
pub const prepareGlyphFrame = glyph_frame.prepareGlyphFrame;
pub const textConfigFromFontSize = state.textConfigFromFontSize;
pub const deviceScaleFromMilli = state.deviceScaleFromMilli;
pub const deviceFontSizeFromMilli = state.deviceFontSizeFromMilli;
pub const uvRectForSlot = glyph_quads.uvRectForSlot;

test {
    // Aggregate this layer's child-file tests into the build. refAllDecls is
    // shallow and does not recurse through the maru barrel, so without this
    // block the unit tests in renderer/* never compile into `zig build test`.
    @import("std").testing.refAllDecls(@This());
}
